### ISSUE TITLE
Переход на новый рендер

### ISSUE THREAD

**Issue by chigov** [ElectroService/WAP#117]
- [x] Форма статистики продаж
- [x] Форма динамики продаж
- [x] TableView - изменение в шапке при появлении/исчезновении скрола
- [x] TableView - сплиттеры столбцов
- [x] TableView - экспорт
- [x] История продаж - сжимается левая панель по вертикали
- [x] История продаж - в группировке при клике на "Показать детализацию" строка не становиться выбранной

**Comment by RomulT** [comment]
Возможно имеет смысл изменения по TableView из ветки #117-forms-MKS перенести в master.
